--- # handler example
- hosts: localhost
  become: yes
  vars:
    httpd_log_level: error
  tasks:
    - name: installed apache2
      apt:
        name: apache2
        state: latest
    - name: update configuration
      template:
        src: /home/ansible/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
      notify: httpd service
  handlers:
    - name: httpd service handler
      service:
        name: httpd
        state: restart
      listen: httpd service