--- # loop example
- hosts: localhost
  become: yes
  tasks:
    - name: Loop example to install software
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - elinks
        - nmap-ncat
        - bind-utils

 # Loop returns a ansible variable called item to the apt